name = 'Recipes'
license = 'MIT'
licenselink = 'https://github.com/Rasalas/hugo-theme-recipes/LICENSE'
description = 'A simple and clean theme for Hugo to display your recipes'
version = 1

# The home page of the theme, where the source can be found
homepage = 'https://github.com/Rasalas/hugo-theme-recipes'

# If you have a running demo of the theme
#demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['recipes', 'food', 'cooking']
features = []


# If the theme has a single author
[author]
  name = 'Torben Buck'
  homepage = 'https://www.tbuck.de'